### ISSUE TITLE
Question about R^2 and scale invariance

### ISSUE THREAD

**Issue by huiyang-yi** [CausalDisco/CausalDisco#2]
Hi,
I'm looking for a formal proof or a detailed explanation regarding the scale invariance of R^2.
Is there a proof that R^2 is scale-invariant? If such a proof or detailed explanation exists, could you please provide it or point me towards relevant resources?
Thanks.

**Comment by Scriddie** [comment]
Thanks for your interest in the theoretical part of our work. The scale-invariance of $R^2$ is usually taken for granted and not discussed much, so let me attempt an answer here. I will start from a slight adaptation using of the definition in https://arxiv.org/pdf/2303.18211.pdf (top of page 5) using just two random variables $X$ and $Y$:

$$R^2 = 1 - \frac{\text{Var}(Y - E(Y|X))}{\text{Var}(Y)}.$$

Given that $E(cY|X) = cE(Y|X)$ for some nonzero constant $c$, one can see that scaling $Y$ by a factor of $c$ does not affect $R^2$.

The case is more subtle if $X$ is scaled. Let $Z = cX$ be the random variable obtained by multiplying $X$ with a nonzero constant $c$. The elements of the sigma-algebra $\sigma(Z)$ have a one-to-one correspondence to those of $\sigma(X)$ and there is thus no change in the conditional relationship between $Y$ and $X$. Consequently, we have that $E(Y|Z) = E(Y|cX) = E(Y|X)$, meaning that $R^2$ is also invariant to scaling in $X$. The case for multiple variables holds for the same reason.

I hope that helps and let me know if you have any questions!

**Comment by huiyang-yi** [comment]
Thanks for your patient explanation, I have understood the scale-invariance of R^2.
